import os

# Paths (パッケージの親ディレクトリの data フォルダを指す)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR_NAME = "data"

# Tuning Settings
DEFAULT_LEARN_HOURS = 24
AUTO_LEARN_ENABLED = True
MIN_PREDICTION_CONFIDENCE = 0.40

# Retention — 全データは 90 日保持、超過分は古いものから自動削除
DATA_RETENTION_DAYS = 90
HISTORY_RETENTION_DAYS = DATA_RETENTION_DAYS
COUNTER_RETENTION_DAYS = DATA_RETENTION_DAYS
METRIC_RETENTION_HOURS = DATA_RETENTION_DAYS * 24
LOG_RETENTION_DAYS = DATA_RETENTION_DAYS
EVAL_STATE_RETENTION_DAYS = DATA_RETENTION_DAYS
GNN_TRAINING_RETENTION_DAYS = DATA_RETENTION_DAYS

# ROI Parameters
COST_PER_HOUR = 6000
MINUTES_PER_ALERT = 15
IMPACT_COST_FACTOR = 10000
ROI_CONSERVATIVE_FACTOR = 0.8

# Risk Weights
WEIGHT_SEMANTIC = 2.0
WEIGHT_TREND = 1.5
WEIGHT_VOLATILITY = 1.5
WEIGHT_TOPOLOGY = 1.0
WEIGHT_HISTORY = 1.0
WEIGHT_INTERACTION = 2.0
GLOBAL_SIGMOID_BIAS = 0.5

# Shadow Mode / Auto-Tuning Gates
SHADOW_MIN_HOURS_SINCE_PROPOSED = 24
SHADOW_MAX_FN_DELTA = 0
SHADOW_MIN_FP_REDUCTION = 0.05
SHADOW_MIN_RECALL_MARGIN = 0.0
SHADOW_MAX_THRESHOLD_DELTA = 0.02
SHADOW_PASS_HISTORY_MAX = 8
PROMOTE_REQUIRED_CONSECUTIVE_PASSES = 2

# Constants
GLOBAL_IGNORE_PHRASES = ["dry-run", "test message", "synthetic-monitor", "healthcheck"]
ENV_SECRET_B64 = "DIGITAL_TWIN_TENANT_SECRET_B64"
ENV_SECRET_KEY_ID = "DIGITAL_TWIN_KEY_ID"
ENV_RULES_SOT = "DIGITAL_TWIN_RULES_SOT"  # "json" or "db"

# Outcome Definitions
OUTCOME_CONFIRMED = "confirmed_incident"
OUTCOME_FALSE_ALARM = "false_alarm"
OUTCOME_MITIGATED = "mitigated"
OUTCOME_MISSED = "missed_incident"
OUTCOME_SUSPECTED_MAINTENANCE = "suspected_maintenance"
OUTCOME_PLANNED_MAINTENANCE = "planned_maintenance"

# Lock Config
LOCK_TIMEOUT_SEC = 5.0    # ★ 30→5秒: Streamlit UIがハングしないよう短縮
LOCK_TTL_SEC = 15.0       # ★ 60→15秒: ステールロック検出を高速化
LOCK_POLL_SEC = 0.05      # ★ 0.1→0.05秒: ポーリング間隔を短縮
